---
resources:
- name: web-app
  type: git
  source:
    uri: git@github.com:slhommed/spring_task_app.git
    private_key: {{repo-private-key}}

- name: deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
- name: assemble-app
  serial: true
  plan:
  - get: web-app
  - task: build-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: springcloud/pipeline-base}
      inputs:
      - name: web-app
      outputs:
      - name: app-build
      run:
        dir: web-app
        path: sh
        args:
        - -exc
        - |
          ./gradlew  assemble
          rsync -av ./manifest.yml app-build/
          rsync -avr ./build/ app-build/build/
          ls -al app-build/
  - task: build-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: app-build
      run:
        path: sh
        args:
        - -exc
        - |
          ls -al app-build/
  - put: deploy-web-app
    inputs:
    - name: app-build
    params:
      manifest: app-build/manifest.yml

